#!/bin/bash
set -e

if [ "$#" -ne 1 ]; then
    echo "Usage: deploy <project url>"
    exit 1
fi

ACTIVESTATE_API_HOST="$(echo "$1" | awk -F'/' '{print $3}')"
ORG="$(echo "$1" | awk -F'/' '{print $4}')"
PROJECT="$(echo "$1" | awk -F'/' '{print $5}')"

export ACTIVESTATE_API_HOST
state auth
state checkout ${ORG}/${PROJECT} --portable --force --runtime-path "/workdir/${PROJECT}"

exit 0
